# vim: ft=yaml.docker-compose
---
name: atuin

include:
  - ext/docker-compose-snippets/tailscale-caddy.yaml
  - ext/docker-compose-snippets/simple-reverse-proxy.yaml
  - ext/docker-compose-snippets/volume-backup-schedules.yaml

services:
  atuin:
    image: ghcr.io/rahulsalvi/atuin:latest
    command: server start
    restart: unless-stopped
    environment:
      ATUIN_HOST: 127.0.0.1
      ATUIN_PORT: 8080
      ATUIN_OPEN_REGISTRATION: true
      ATUIN_DB_URI: sqlite:///config/atuin.db
    volumes:
      - atuin-data:/config
    extends:
      file: ext/docker-compose-snippets/tailscale-app-base.yaml
      service: tailscale-app-base

  backup:
    volumes:
      - atuin-data:/backup:ro
    extends:
      file: ext/docker-compose-snippets/volume-backup.yaml
      service: aws-backup-frequent

volumes:
  atuin-data:
